source 'https://github.com/CocoaPods/Specs.git'

target 'WatchTasksApp' do
    pod "WatchTasks", :path => "../"
end

target 'WatchTasksApp WatchKit Extension' do
    pod "WatchTasks", :path => "../"
end
